version: '3.2'
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-cypress-ui
    environment:
      - CYPRESS_baseUrl=https://todomvc.com
    command: npm run cy:run
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.js:/app/cypress.config.js
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/screenshots:/app/cypress/screenshots